nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN}"

npmScopes:
  ramm:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/54281288/packages/npm/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
