nodeLinker: node-modules

npmScopes:
  ramm:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/54281288/packages/npm/"
    npmAuthToken: "${GITLAB_AUTH_TOKEN}"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
